{
    'name': 'member_web',
    'version': '1.0',
    'summary': 'member_manage',
    'category': 'member',
    'author': 'om',
    'website': 'https://www.yourwebsite.com',
    'depends': ['base','website','product','web','account'],
    'data': [
        'security/ir.model.access.csv',
        'security/rule.xml',
        'views/register.xml',
        'views/member.xml',
        'views/membership.xml',
        'views/duration.xml',
        'data/sequence.xml',
        'data/cron_exp.xml',
        'data/cron_rem.xml',
        'data/cron_renew.xml',
        'data/reminder.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}